### ISSUE TITLE
Issue with angular-file-upload

### ISSUE THREAD

**Issue by forcewill** [shaungrady/angular-http-etag#24]
When using `angular-http-etag` together with `angular-file-upload` we get the following error:

`Uncaught TypeError: Cannot read property 'transformResponse' of undefined`

The error comes from this piece of code in [`angular-file-upload`](https://github.com/nervgh/angular-file-upload)  FileUploader.js lines 392-398
`  _transformResponse(response, headers) {
            var headersGetter = this._headersGetter(headers);
            forEach($http.defaults.transformResponse, (transformFn) => {
                response = transformFn(response, headersGetter);
            });
            return response;
        }`

I've [opened](https://github.com/nervgh/angular-file-upload/issues/665) this issue here and in [`angular-file-upload`](https://github.com/nervgh/angular-file-upload)

**Comment by shaungrady** [comment]
Fix has been published to `npm`, version 2.0.3. Thanks for the bug report!

**Comment by forcewill** [comment]
Thanks for the fast fix @shaungrady
