### ISSUE TITLE
Angular Decorator not working

### ISSUE THREAD

**Issue by Tommatheussen** [shaungrady/angular-http-etag#43]
I've been having problems with using this module.
Every time I try to use the .cached method, the application complains, stating that `$http.get().then().cached` not a function is.

I noticed you decorate the $http service in the .run block, moving the decorator the the config block removes the issue and make the module work correctly for me. Is there a specific reason why it is done in the .run block? (placing logs revealed that the decorator is not fired in the .run block)

Using the latest angular version (1.5.8) currently, tested with previous versions as well, but didn't seem to work either.

**Comment by shaungrady** [comment]
Seems I made a bad assumption about the injected services in the decorator not being available in the config block. Thanks for bringing this to my attention! It has been fixed in version `2.0.13`.

**Comment by Tommatheussen** [comment]
Nice, thanks for the fast fix :)
