### ISSUE TITLE
Not waiting for response from server

### ISSUE THREAD

**Issue by Tommatheussen** [shaungrady/angular-http-etag#45]
I found this issue when trying to use get data after a delete action was executed.

Imagine the following scenario:
1. Web page loads list of entries, and stores the ETAG for later use
2. User navigates to different web page inside same application (keeping the ETAG in memory), then navigates back to the page
3. The application loads data from ETAG caching correctly
4. User deletes one entry from the list (inside the web application)
5. After successful delete the application reloads the list (to make sure it's up to date, why reload? Because it's using pagination and we want to have a full list)
6. The OLD list is still kept in memory and returned demo the .cached method
7. The http request finishes with new data, but is not being used since the old data got returned already

I might be wrong here, but it looks like the `.cached` method is not waiting for the http request to finish and check if it has new data or not.
example I used to test this: 
```
function getSeen() {
    return $q(function (resolve, reject) {
        $http.get('/api/seen/', { etagCache: true })
            .success(dataReturned)
            .cached(dataReturned)
            .error(errorCaught);
                
        function dataReturned(data, status, headers, config, itemCache) {
            console.log('loading finished, returned status: ', status);
            resolve(data);
        }

        function errorCaught(data, status) {
            if (status !== 304) {
                console.log('error occured:', data);
                reject(data);
            }
        }
    });
}
```

This code is placed inside a service, called from a controller. The logs look like this:
```
loading finished, returned status:  200 (Step 1, initial load)
loading finished, returned status:  cached (Step 3, reloading a same data)
loading finished, returned status:  cached (Step 6, old cached data is returned)
loading finished, returned status:  200 (step 7, new data is returned from server)
```
I haven't looked at the code yet, but I'll try to see how it's working and try to submit a PR to fix this

**Comment by shaungrady** [comment]
You're correct that `.cached` is a synchronous method. That was a conscious design decision to provide greater responsiveness to applications—why go through the trouble of caching data and not provide a way for applications to make use of it ASAP? So this isn't something I consider needing a "fix."

With regard to your code snippet, it's a little strange that you're wrapping the `$http` promise in another promise. Looking at the code in the `Flexget` repo that referenced this issue, it seems to me there are a couple solutions:

1. Refactor out the `$q` and rewrite other parts of the app that make use of `seenService` to be aware of the `cached` method that's added to the `$http` promise.

2. Have calls to the `deleteEntryById` delete the cache item so that the `cached` function isn't called. E.g.:

  ```javascript
  function deleteEntryById(id) {
    return $http
      .delete('/api/seen/' + id + '/')
      .success(function () {
        httpEtag
          .getCache()
          .unsetItem('/api/seen/')
      })
      .catch(callFailed);
  }
  ```

  This would also need to be added everywhere else in the app where the seen data is manipulated.

**Comment by Tommatheussen** [comment]
I wanted to be able to use the service (that calls the http methods) easily by just calling the service's method and accessing the data using the `.then` method. Which Is why I have now wrapped the `$http` promise with another promise (so I could access cached data with `.then` as well). If you check other services that load data from the API, you'll notice they aren't wrapped in the extra promise ;)

I suppose I could change the calls to the seenService to use the `.cached` method directly.
clearing the cache in delete/put/post methods could also be possible, but I guess it'll be more error-prone, since you'd have to make sure the correct item is unset.

Anyways, thanks for the explanation why it was designed this way :)
I'll close this as it's by design.

**Comment by shaungrady** [comment]
Another hacky option would be to do something like this:

``` javascript
        $http.get('/api/seen/', { etagCache: true })
            .success(dataReturned)
            .cached(dataReturned)
            .error(function (data, status) {
                if (status === 304) resolve(httpEtag.getCache().getItem('/api/seen/'))
                else reject(data)
            });
```

**Comment by Tommatheussen** [comment]
Hmm, I believe that would still return the old cached data first, before the call finishes (if I were to leave it like this, wrapped in the `$q` promise).

If you mean it without the `$q` promise, then it might work, but I guess it's no advantage over catching the `.cached` method inside the controllers.

Changing my code right now, using the `.cached` method in the controllers seems to be a good solution, it looks nicer then I was expecting it to be.
