### ISSUE TITLE
[Question] Header caching

### ISSUE THREAD

**Issue by Tommatheussen** [shaungrady/angular-http-etag#46]
Is there a way to cache certain headers returned from the server as well?

we're currently changing our API and front end to make sure we can use ETAGs, use well as server side pagination (with Link headers).

Currently using this module we can't use link headers and ETAGs on the same endpoint.

**Comment by shaungrady** [comment]
There are undocumented methods which allow you to access the underlying cache object which you can use:

``` javascript
.success(function (data, status, headers, config, itemCache) {
  var rawCache = itemCache.$get()
  rawCache.myHeader = headers('my-header')
  itemCache.$set(rawCache)
})
.cached(function (data, status, headers, config, itemCache) {
  var myHeader = itemCache.$get().myHeader
})
```

Be sure not to mess around with the `etagHeader` or `responseData` properties on that object as they're used by the service.

**Comment by shaungrady** [comment]
``` javascript

```

**Comment by shaungrady** [comment]
It can also be accessed via a cache object like so (in this example, straight from the injected service):

``` javascript
var defaultCache = httpEtag.getCache()
var rawCacheValue = defaultCache.$getItem('/itemkey')

rawCacheValue.myHeader = myHeaderValue
defaultCache.$setItem('/itemkey', rawCacheValue)
```
