### ISSUE TITLE
This does not give me 304 status

### ISSUE THREAD

**Issue by viveksi** [shaungrady/angular-http-etag#8]
I used this in my app for simple GET request, but it's not returning me 304 response and always returns result from the server.

Do i need to make any code changes in my service(c#) to modify the response header. As i thought this will do the same automatically. As angular does not by default support ETAG and returns 200 response for even 304

Let me know if i'm missing something here

**Comment by shaungrady** [comment]
Is your server generating ETag headers? Use the network panel of your browser's developer tools and look for a response header resembling `ETag:"5e8c52243790d1621ebbaab45bf1ad7b"`

**Comment by viveksi** [comment]
Yes it is below is the response from Dev Tool, I get 304 in console, but the promise return me 200, i believe this is because of angular. http://stackoverflow.com/questions/1665082/http-status-code-200-cache-vs-status-code-304


Remote Address:127.0.0.1:8888
Request URL:http://localhost:3000/xxxxxxxxxx
Request Method:GET
Status Code:304 Not Modified
Response Headers
view source
Access-Control-Allow-Credentials:true
Access-Control-Allow-Origin:http://localhost:4000
Connection:keep-alive
Date:Wed, 16 Sep 2015 12:18:18 GMT
ETag:"1913595015"
Tracking:029c5a60-5c6d-11e5-bf0c-a9ed6611ce1f
X-Cache:MISS
X-Powered-By:Express
Request Headers
view source
Accept:application/json, text/plain, */*
Accept-Encoding:gzip, deflate, sdch
Accept-Language:en-US,en;q=0.8
Host:localhost:3000
If-None-Match:"1913595015"
Origin:http://localhost:4000
Proxy-Connection:keep-alive
Referer:http://localhost:4000/xxxxxx
requestid:81868881-867d-4d9d-d7f7-c0e077652a09
User-Agent:Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.93 Safari/537.36
Name

**Comment by shaungrady** [comment]
Angular doesn't modify 304s. It treats 304s as an error since no response data is returned by the server, so a successful response isn't possible. This module doesn't modify the response in any way—304s are still treated as errors. If you remove the `angular-http-etag` module, do you still experience the same response?

**Comment by viveksi** [comment]
yes, I'm seeing the same response, no change, i looked at my code base we are not modifying it either from any interceptor or anything, Can i be assured that if i use angular-http-etag i don't have to handle them on server side and return 304 response

**Comment by shaungrady** [comment]
The only thing `angular-http-etag` needs to function properly is the `ETag` response header. When the module sees that header, it remembers it (as well as caches the response data), and sends it back to the server when the request is repeated via the `If-None-Match` request header. If the ETag sent to the server via the `If-None-Match` request header is the same as the ETag that the server generates when fulfilling the request are the same, the server will respond with a 304 and no response data payload. `angular-http-etag` does nothing in these cases. However, if the request is a 200, that means that the data has changed on the server, and the module updates the ETag and response data cache for that request.

If you're seeing the request response as a 304 in the dev tools, and `$http` is interpreting it as a 200, something else is happening.
