### ISSUE TITLE
LICENSE file

### ISSUE THREAD

**Issue by peah90** [shaungrady/angular-http-etag#83]
Can you put a ``LICENSE.md`` file in your repository?
You specified the MIT license in ``package.json``, but that is not sufficient for me to use your library.

**Comment by shaungrady** [comment]
No problem. If you want to open a PR, it'd be much appreciate--otherwise the soonest I'll get it fixed next week.

**Comment by shaungrady** [comment]
This has been published to npm as `2.0.17`.

**Comment by peah90** [comment]
Thank you very much! :-)
